### ISSUE TITLE
Estimators could be replaced by zoomed fft?

### ISSUE THREAD

**Issue by Counterfeiter** [l-pio/mmwranging#1]
Hello,

very well written repo and interesting piece of hardware with incredible bandwidth...
One little question so far:

Why did you use this "basic" cubic interpolation to improve the resolution of the fft? There are solutions like zoomed FFT and CZT, did you see any advantages in the cubic interpolation?

Best regards

Sebastian

**Comment by l-pio** [comment]
Hi Sebastian,

Thank you for your positive feedback!

Modified quadratic interpolation in the power-scaled magnitude response (with a tuning parameter optimized to the pulse waveform, i.e., the window function) turned out to be a very efficient method.
Refining the resolution using a single zoom FFT or iteratively refining the resolution using multiple zoom FFTs has a higher computational cost to achieve a sufficient-or at least comparable-resolution.

Regards
Lukas

**Comment by Counterfeiter** [comment]
Hi Lukas,

I think it depends on the hardware. Taking the log10 of a large spectrum is a bottleneck on my microcontroller. On PC (x86 or higher) side there are native processor floating point commands for log10. But the limited instruction set of a CortexM FPU has  the opportunity to do a faster log2 approximation. But if I get it right, the log10 instructions could minimized if the peak is searched in non log and only the desired support points will be calculated. 

I have a hard time to understand whats difference it makes to have no IQ receiver (two channel). If I get it right, your spectrum approximation must be two times more precise because you have only information about -90 to 90° and not the full quadrant information from tan2. In your paper in Figure 4. there is "coarse ToF estimate". This estimate is based on the frequency sweep and phase information based on this sweep. In my opinion no ToF, because it is based on FMCW and any air condition cancel out. Or is there a special case for just I receivers?

Best regards

Sebastian

**Comment by l-pio** [comment]
Hi Sebastian

You don't need to peak search in the log radar echo. 
You only need to compute y^p (with a fractional p) for the samples nearest the peak, which is somehow computationally intensive (but it's just for three values).

As the radar echo is a causal system, you don't need an IQ receiver provided sufficient bandwidth [otherwise, you have interfering sidelobes of the mirrored components h(t)=h^*(-t)]. With IQ data, the reading is more precise; however, as I and Q data are partially correlated, the increase in SNR should be significantly less than 3 dB).

I didn't get your last question. There is a coarse estimate based on the pulse position (i.e., the intermediate frequency) and a fine estimate based on the pulse phase. The ambiguous phase is unwrapped using the coarse pulse position estimate.

Regards
Lukas

**Comment by skuep2** [comment]
Just for reference, the algorithm behind the work of Lukas will be available in our Radar Sensors soon. They use a 528 MHz Cortex-M7 and achieve a Measurement-Rate of 1kHz, including the fixed-point FFT, interpolations and estimator.

This would probably never have been possible using an iterative FFT approach. But I agree, that it takes some optimization and approximation (of some functions such as atan2 or the y^p mentioned by Lukas) to get it working well on an embedded system.

Best Regards
Simon (https://www.2pi-labs.com)

**Comment by Counterfeiter** [comment]
@l-pio I am still a bit confused. Why do the phase estimator classes use the wording "magn_response" and "phase_response": https://github.com/l-pio/mmwranging/blob/d2770aa3424fc998652239738fb311705e4d923e/mmwranging/estimator.py#L7
What make sense in my point of view. But the input seems to be time domain data:
https://github.com/l-pio/mmwranging/blob/d2770aa3424fc998652239738fb311705e4d923e/mmwranging/processor.py#L340

Maybe I am confused between time domain and frequency domain its used here in a different way as I suspect. 

@skuep2 That sounds great! With a maximum size of 4096 or did you mange it with the 10001 samples from your example?

In my project I am dealing with multipath and clutter from multitarget, measurement speed is about 2 kHz to come down to a 30 µm resolution. But because of the clutter the resolution is not my problem.

Best regards 
Sebastian from Leipzig

**Comment by l-pio** [comment]
From a system theory viewpoint, it is advantageous to understand the input data as frequency domain data, as every sample refers to a certain RF frequency. Then, you have a common description for pulse radar and FMCW radar, where the FMCW radar is like a pulse radar with pulse compression.

Regards
Lukas
